### ISSUE TITLE
As Admin I Want to Login to Qbot Admin so That I Can Manage Quote

### ISSUE THREAD

**Issue by aalfaiz** [aalfaiz/Qbot#1]
- [ ] As Admin I Want to Add Quote
- [ ] As Admin I Want to Change Quote
- [ ] As Admin I Want to Delete Quote
